[package]
name = "chainstate-launcher"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

chainstate = { path = ".." }
chainstate-storage = { path = "../storage" }
common = { path = "../../common" }
logging = {path = '../../logging'}
storage = { path = "../../storage" }
storage-inmemory = { path = "../../storage/inmemory" }
storage-lmdb = { path = "../../storage/lmdb" }
utils = { path = '../../utils' }
