[package]
name = "node-daemon"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logging = { path = "../logging" }
node-lib = { path = "../node-lib/" }

tokio = { workspace = true, default-features = false }

anyhow = "1.0"

[dev-dependencies]
assert_cmd = "2"
