[package]
name = "accounting"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = '../common'}
serialization = {path = "../serialization"}
utils = {path = '../utils'}

thiserror = "1.0"
parity-scale-codec = "3.1"

[dev-dependencies]
proptest = "1.0"
rstest = "0.16"
