[package]
name = "storage-inmemory"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

# Local dependencies
storage-core = { path = "../core" }

[dev-dependencies]
utils = { path = "../../utils" }
storage-backend-test-suite = { path = "../backend-test-suite" }

[[test]]
name = "backend"
harness = false
