[package]
name = "api-server-stack-test-suite"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
api-blockchain-scanner-lib = { path = "../scanner-lib" }
api-server-common = { path = "../api-server-common" }
api-web-server = { path = "../web-server" }
chainstate = { path = "../../chainstate" }
chainstate-test-framework = { path = "../../chainstate/test-framework" }
common = { path = "../../common" }
crypto = { path = "../../crypto" }
logging = { path = "../../logging" }
randomness = { path = "../../randomness" }
serialization = { path = "../../serialization" }
test-utils = { path = "../../test-utils" }
utils = { path = "../../utils" }
pos-accounting = { path = "../../pos-accounting" }
node-comm = { path = "../../wallet/wallet-node-client" }
mempool = { path = "../../mempool" }

async-trait.workspace = true
axum.workspace = true
ctor.workspace = true
hex.workspace = true
libtest-mimic.workspace = true
reqwest = "0.11"
rstest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
