[package]
name = "serialization"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arraytools = "0.1.5"
hex-literal = "0.3.4"
parity-scale-codec = {version = "2.3.1", features = ["derive", "chain-error"]}
rand = "0.8.4"

#[dev-dependencies]
# All files in tests folders for Rust seems like other crates,
# and the proper way to hide types that we need in these files to tests is to make a nested crate.
serialization-utils = { path = "./serialization-utils" }
