[package]
name = "storage-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

# Local dependencies
common = { path = '../../common' }
logging = { path = '../../logging' }

# External dependencies
thiserror = "1.0"
