[package]
name = "storage-core"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logging = { path = '../../logging' }
utils = { path = '../../utils' }

itertools.workspace = true
thiserror.workspace = true