[package]
name = "mintlayer"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mintlayer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.11", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.14", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-cli = "2.0.0-rc.1"
tauri-plugin-clipboard-manager = "2.1.0-beta.7"
tauri-plugin-dialog = "2"
tauri-plugin-http = "2.0.0-rc.5"
tauri-plugin-updater = "2.0.0-rc.3"
tauri-plugin-os = "2.0.0-rc"
tauri-plugin-single-instance = "2.0.0-rc"
tauri-plugin-notification = "2.0.0-rc"
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chainstate = {path = "../../chainstate"}
common = { path = "../../common" }
crypto = { path = "../../crypto" }
logging = {path = "../../logging"}
mempool = { path = "../../mempool" }
node-lib = { path = "../../node-lib" }
node-comm = { path = "../../wallet/wallet-node-client" }
p2p = { path = "../../p2p" }
serialization = { path = "../../serialization" }
subsystem = { path = "../../subsystem" }
utils = { path = "../../utils" }
wallet = { path = "../../wallet" }
wallet-controller = { path = "../../wallet/wallet-controller" }
wallet-types = { path = "../../wallet/types" }
wallet-rpc-lib = { path = "../../wallet/wallet-rpc-lib"}
wallet-rpc-client = { path = "../../wallet/wallet-rpc-client"}
wallet-cli-commands = { path = "../../wallet/wallet-cli-commands"}

anyhow.workspace = true
chrono.workspace = true
futures.workspace = true

rfd = { workspace = true, features = ["xdg-portal", "tokio"] }
thiserror.workspace = true
tokio.workspace = true
variant_count.workspace = true
tauri-plugin-process = "2"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
