[package]
name = "constraints-value-accumulator"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
crypto = { path = "../../crypto" }
orders-accounting = { path = "../../orders-accounting" }
pos-accounting = { path = "../../pos-accounting" }
tokens-accounting = { path = "../../tokens-accounting" }
randomness = { path = "../../randomness" }
utils = { path = "../../utils" }
utxo = { path = "../../utxo" }

thiserror.workspace = true

[dev-dependencies]
accounting = { path = "../../accounting" }
common-test-helpers = { path = "../../common/test-helpers" }
test-utils = { path = "../../test-utils" }

rstest.workspace = true
