[package]
name = "p2p-test-utils"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chainstate = { path = "../../chainstate/" }
chainstate-storage = { path = "../../chainstate/storage" }
chainstate-test-framework = { path = "../../chainstate/test-framework" }
common = { path = "../../common/" }
crypto = { path = "../../crypto/" }
mempool = { path = "../../mempool/" }
subsystem = { path = "../../subsystem/" }
test-utils = { path = "../../test-utils" }
utils = { path = "../../utils" }

portpicker.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
tracing.workspace = true
