[package]
name = "wallet-address-generator"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors = [
    "Samer Afach <samer.afach@mintlayer.org>",
    "Ben Marsh <benjamin.marsh@mintlayer.org>",
    "Enrico Rubboli <enrico.rubboli@mintlayer.org>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
utils = { path = "../../utils" }
wallet-controller = { path = "../wallet-controller" }
wallet-address-generator-lib = { path = "../wallet-address-generator-lib" }
wallet-types = { path = "../types" }
wallet = { path = "../../wallet" }
crypto = { path = "../../crypto" }

clap = { workspace = true, features = ["derive"] }

thiserror.workspace = true
