[package]
name = "chainstate-types"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common/" }
crypto = { path = "../../crypto" }
logging = { path = '../../logging' }
serialization = { path = "../../serialization" }
storage = { path = "../../storage/" }
utils-in-mem-item-tree = { path = "../../utils/in_mem_item_tree" }

derive_more.workspace = true
enum-iterator.workspace = true
generic-array.workspace = true
num-derive.workspace = true
num-traits.workspace = true
parity-scale-codec.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
