[package]
name = "chainstate-types"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialization = { path = "../../serialization" }
common = { path = "../../common/" }
storage = { path = "../../storage/" }
crypto = { path = "../../crypto" }

thiserror.workspace = true
parity-scale-codec.workspace = true
generic-array = "0.14"
