[package]
name = "consensus"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockchain-storage = { path = '../blockchain_storage'}
common = { path = '../common'}
rand = "0.8.4"
logging = { path = '../logging'}
thiserror = "1.0.30"
proptest = "1.0.0"
parity-scale-codec-derive = "2.3.1"
parity-scale-codec = {version = "2.3.1", features = ["derive", "chain-error"]}