[package]
name = "consensus"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
common = {path = '../common'}
utils = {path = "../utils"}
chainstate-types = {path = '../chainstate/types'}
pos_accounting = {path = '../pos_accounting'}
utxo = {path = '../utxo'}

thiserror.workspace = true
num = "0.4.0"

[dev-dependencies]
rstest = "0.16"
