[package]
name = "storage-lmdb"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logging = { path = '../../logging' }
storage-core = { path = '../core' }
utils = { path = '../../utils' }

# Commit "Fix off_t overflow on Windows"
lmdb-mintlayer = { git = 'https://github.com/mintlayer/lmdb-rs-mintlayer.git', rev = '88d9f2bd49399f75ca1baa1537b2387252f9b5db' }

[dev-dependencies]
rstest.workspace = true
storage-backend-test-suite = { path = "../backend-test-suite" }
tempfile.workspace = true
test-utils = { path = "../../test-utils" }

[[test]]
name = "backend"
harness = false
