on:
  push:
    branches:
      - "**" # target all branches
  pull_request:
    branches:
      - master

name: Code Coverage

env:
  # We partition coverage tests into multiple parts to avoid filling diskspace in a single runner
  PARTITIONS_COUNT: 3

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # This range spans from `0` to `PARTITIONS_COUNT - 1`, where `PARTITIONS_COUNT` is the number of partitions (defined in env var above)
        partition: [0, 1, 2]

    steps:
      - name: Install dependencies
        run: sudo apt-get install -yqq --no-install-recommends build-essential libgtk-3-dev python3 python3-toml
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-08-01
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: Run coverage tests
        run: python3 build-tools/workspace-partition.py ${{ env.PARTITIONS_COUNT }} ${{ matrix.partition }} -p | xargs cargo test
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: full
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
      - id: coverage
        uses: actions-rs/grcov@v0.1
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ${{ steps.coverage.outputs.report }}
