[package]
name = "serialization-core"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive", "chain-error", "std"] }

[dev-dependencies]
arraytools.workspace = true
hex-literal.workspace = true
rand.workspace = true
