[package]
name = "serialization-core"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive", "chain-error"] }

[dev-dependencies]
arraytools = "0.1"
hex-literal = "0.3"
rand = "0.8"
